### ISSUE TITLE
Routes not working in production

### ISSUE THREAD

**Issue by mohdomama** [amu-oss/amu2ias-frontend#14]
The sub-pages can be accessed from navigation drawer but if the same url is directly entered, is throws 404. (Wroks fine on localhost)
Steps to reproduce:
- Open https://mohdomama.github.io and click on `Hall of Fame`. This will work.
-  Open https://mohdomama.github.io/fame . This will not work

Possible cause :
- we are using the `history` mode in routing. I am not sure.

**Comment by mohdomama** [comment]
@iamareebjamal what do you think ?

**Comment by iamareebjamal** [comment]
Check out https://amu2ias.surge.sh

The same will happen here, and yes, because of history mode, because the router will not be kicked until the app is loaded and the /blah endpoint will not trigger the app. This is because the request handler will try to look for /blah document and not load index.html

If we disable the history mode, endpoints will look like this site/#/blah so the site will always be triggered and router will be loaded because #/blah is just a URL fragment

The solution is to redirect each request to index.html which is not possible in github. Not sure about surge

But when we will deploy to firebase hosting, it will work as it has option as default to redirect it

**Comment by mohdomama** [comment]
Same problem

**Comment by iamareebjamal** [comment]
@mohdomama Updated the comment, clicked on comment before completing it

**Comment by iamareebjamal** [comment]
https://surge.sh/help/adding-a-200-page-for-client-side-routing

**Comment by mohdomama** [comment]
Thanks @iamareebjamal for the comprehensive answer :smiley:
